software-mansion-labs/expensify-app-fork

- src/components/MenuItem.tsx
- src/pages/home/sidebar/AllSettingsScreen.tsx
- src/pages/settings/InitialSettingsPage.js
- src/pages/settings/Wallet/WalletPage/WalletPage.js
- src/styles/index.ts
> @cdOut/ideal nav fixes 2

- src/components/WorkspaceSwitcherButton.tsx
- src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/TopBar.tsx
- src/libs/Navigation/linkTo.ts
- src/libs/Navigation/linkingConfig/getMatchingBottomTabRouteForState.ts
- src/libs/ReportUtils.ts
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fixes 203, 207

- src/CONST.ts
- src/components/AvatarWithImagePicker.js
- src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
- src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/index.tsx
- src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.ts
- src/libs/Navigation/AppNavigator/getPartialStateDiff.ts
- src/libs/Navigation/linkTo.ts
- src/libs/PolicyUtils.ts
- src/libs/actions/Report.ts
- src/pages/home/sidebar/AllSettingsScreen.tsx
- src/pages/workspace/WorkspacePageWithSections.tsx
- src/types/onyx/Policy.ts
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Refactor comments

- src/libs/Notification/PushNotification/subscribeToReportCommentPushNotifications.ts
- src/libs/PolicyMembersUtils.ts
- src/libs/actions/Report.ts
- src/pages/WorkspaceSwitcherPage.js
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Refactor workspace switcher and PolicyMembersUtils

- src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
- src/libs/actions/Report.ts
- src/libs/actions/Session/index.ts
- src/libs/actions/Welcome.ts
https://linear.app/expensify-swm/issue/EXP-275/[wave-9]-new-onboarding-flow-detecting-first-time-users
TODO:
- never show the modal for devs or QA teams
> [Wave9] Detect first time users - check display name and purpose

- src/CONST.ts
- src/ROUTES.ts
- src/components/TabSelector/TabSelector.tsx
- src/languages/en.ts
- src/languages/es.ts
- src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx
- src/libs/Navigation/dismissModal.ts
- src/libs/Navigation/linkingConfig/config.ts
- src/pages/share/ShareRootPage.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> feat: add root & confirmation screens

- src/SCREENS.ts
- src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx
- src/libs/Navigation/AppNavigator/Navigators/FullScreenNavigator.tsx
- src/libs/Navigation/AppNavigator/Navigators/LeftModalNavigator.tsx
- src/libs/Navigation/linkingConfig/config.ts
- src/libs/Navigation/types.ts
- src/pages/SearchPage/index.tsx
- src/styles/theme/themes/dark.ts
- src/styles/theme/themes/light.ts
- tests/perf-test/SearchPage.perf-test.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Remove wrapper for lhp screens

- src/components/ConnectToNetSuiteFlow/index.tsx
- src/components/ConnectToNetSuiteFlow/types.ts
- src/components/ConnectToQuickbooksOnlineFlow/index.tsx
- src/components/ConnectToQuickbooksOnlineFlow/types.ts
- src/components/ConnectToSageIntacctFlow/index.tsx
- src/components/ConnectToXeroFlow/index.tsx
- src/components/ConnectToXeroFlow/types.ts
- src/pages/workspace/accounting/AccountingContext.tsx
- src/pages/workspace/accounting/PolicyAccountingPage.tsx
- src/pages/workspace/accounting/utils.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> fix infinite API calls

- src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.ts
- src/libs/Navigation/Navigation.ts
- src/libs/Notification/PushNotification/subscribePushNotification/index.ts
- src/libs/actions/Report.ts
- src/pages/ChatFinderPage/index.tsx
- src/pages/WorkspaceSwitcherPage/index.tsx
- src/pages/workspace/WorkspaceProfilePage.tsx
- src/pages/workspace/WorkspacesListPage.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Add navigateToReportWithPolicyCheck

- src/libs/actions/Policy/Policy.ts
- src/pages/home/sidebar/BottomTabAvatar.tsx
- src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx
- Migrated FloatingActionButton component to `useOnyx` from `withOnyx` and cleaned up a few things, including types
https://github.com/user-attachments/assets/eb38dc1c-ccc4-4b2c-998c-9bcb43057194
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Migrate FloatingActionButton to useOnyx and add small cleanups

- src/components/ParentNavigationSubtitle.tsx
- src/libs/Navigation/AppNavigator/createSplitStackNavigator/usePrepareSplitStackNavigatorChildren.ts
- src/libs/Navigation/Navigation.ts
- src/libs/actions/Report.ts
- src/libs/navigateAfterJoinRequest/index.desktop.ts
- src/libs/navigateAfterJoinRequest/index.ts
- src/libs/navigateAfterJoinRequest/index.web.ts
- src/pages/home/ReportScreen.tsx
- src/pages/workspace/WorkspaceInviteMessagePage.tsx
- src/pages/workspace/WorkspaceJoinUserPage.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Remove shouldEnforceFallback param, add comments

- contributingGuides/NAVIGATION.md
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Changes in doc

- src/libs/Navigation/AppNavigator/Navigators/ReportsSplitNavigator.tsx
- src/libs/Navigation/AppNavigator/createCustomStackNavigator/index.tsx
- src/libs/Navigation/linkTo/index.ts
- src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> performance and matching central screen after deeplink

- src/libs/Navigation/AppNavigator/AuthScreens.tsx
- src/libs/Navigation/AppNavigator/createSplitStackNavigator/usePrepareSplitStackNavigatorChildren.ts
- src/libs/Navigation/AppNavigator/getRootNavigatorScreenOptions.ts
- src/libs/Navigation/Navigation.ts
- src/pages/workspace/WorkspacesListPage.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix animations an goUp for the Workspace list page.

- src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts
This bug was found internaly. Passing params from to splits was broken in `getAdaptedState`
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix passing params from RHP in adapted state

- contributingGuides/NAVIGATION.md
- src/libs/Navigation/linkTo/index.ts
- src/libs/Navigation/linkingConfig/RELATIONS/CENTRAL_PANE_TO_RHP_MAPPING.ts
- src/libs/Navigation/linkingConfig/RELATIONS/LHN_TO_SPLIT_NAVIGATOR_MAPPING.ts
- src/libs/Navigation/linkingConfig/RELATIONS/SEARCH_RHP_SCREENS.ts
- src/libs/Navigation/linkingConfig/RELATIONS/SEARCH_TO_RHP.ts
- src/libs/Navigation/linkingConfig/RELATIONS/SETTINGS_TO_RHP.ts
- src/libs/Navigation/linkingConfig/RELATIONS/SIDEBAR_TO_RHP.ts
- src/libs/Navigation/linkingConfig/RELATIONS/SIDEBAR_TO_SPLIT.ts
- src/libs/Navigation/linkingConfig/RELATIONS/TAB_TO_CENTRAL_PANE_MAPPING.ts
- src/libs/Navigation/linkingConfig/RELATIONS/WORKSPACE_SCREEN_TO_RHP_MAPPING.ts
- src/libs/Navigation/linkingConfig/RELATIONS/WORKSPACE_TO_RHP.ts
- src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts
The case where there is a defined `reportID` is now removed from `getMatchingFullScreenRouteForRoute`
$ INTERNAL
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix the default route in getAdaptedState

- src/libs/Navigation/Navigation.ts
- src/pages/home/sidebar/BottomTabAvatar.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Adjust goUp to handle navigating back when targetState is rootState

- src/libs/Navigation/AppNavigator/PublicScreens.tsx
- src/libs/Navigation/NavigationRoot.tsx
- src/libs/Navigation/types.ts
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Make ReportsSplitNavigator public

- .github/workflows/deploy.yml
- fastlane/Fastfile
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Adjust HybridApp deployment to the added submodule

- src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
- src/libs/Navigation/helpers/index.ts
- src/libs/Navigation/helpers/resetPolicyIDInNavigationState.ts
- src/pages/workspace/WorkspaceProfilePage.tsx
- src/pages/workspace/WorkspacesListPage.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Add resetPolicyIDInNavigationState

- src/libs/Navigation/AppNavigator/AuthScreens.tsx
- src/libs/Navigation/AppNavigator/Navigators/ReportsSplitNavigator.tsx
- src/libs/Navigation/AppNavigator/Navigators/SettingsSplitNavigator.tsx
- src/libs/Navigation/AppNavigator/Navigators/WorkspaceSplitNavigator.tsx
- src/libs/Navigation/AppNavigator/createSplitNavigator/SidebarSpacerWrapper.tsx
- src/libs/Navigation/AppNavigator/createSplitNavigator/index.tsx
- src/libs/Navigation/AppNavigator/useRootNavigatorScreenOptions.ts
- src/libs/Navigation/AppNavigator/useSplitNavigatorScreenOptions.ts
There have to be additional container wrapping splits to make sure the sidebar is visible on Safari.
Besides fixing the linked issue:
- reorganized the `useRootNavigatorOptions` hook
- fixed naming in the `createSplitNavigator`
$ https://github.com/Expensify/App/pull/49539#issuecomment-2603327565
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> fix issue: Web/Safari - LHN and Settings not showing up in Safari

- src/libs/Navigation/AppNavigator/createSplitNavigator/SplitRouter.ts
The correct index wasn't always present. That caused the `findFocusedRoute` function to return the first route instead of the focused one.
$ https://github.com/Expensify/App/pull/49539#issuecomment-2604102638
$ https://github.com/Expensify/App/pull/49539#issuecomment-2603761982
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix issue: mweb Navigation - Bottom tab appears on pages that it should not appear after refreshing app

- src/styles/index.ts
Safari mobile doesn't like position absolute for positioning the bottom tab bar.
$ https://github.com/Expensify/App/pull/49539#issuecomment-2603048033
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix issue: IOU - Cursor is displayed on bottom navigation bar, and composer is hidden behind bottom bar

- src/components/Search/SearchRouter/SearchRouter.tsx
- src/pages/Search/SearchPageNarrow.tsx
This PR fixes 2 issues:
- search menu is displayed behidn status bar when scrolling (bad overflow): https://github.com/Expensify/App/pull/49539#issuecomment-2603346962
- search contextual item for reports missing: https://github.com/Expensify/App/pull/49539#issuecomment-2603331086
https://github.com/user-attachments/assets/43d3e7d3-35fc-4f1f-a94e-4ac6d1f2e0f7
> Fix issues related to Search on new navigation

- src/libs/Navigation/helpers/linkTo/index.ts
- src/pages/Search/SearchPage.tsx
- src/pages/iou/request/step/IOURequestStepCurrency.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix navigation issues

- src/pages/workspace/WorkspacesListPage.tsx
Safe area
$ https://github.com/Expensify/App/pull/49539#issuecomment-2603112549
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix issue: Android - Bottom tab bar appears twice on workspace empty state screen

- src/libs/actions/BankAccounts.ts
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> fix invoices - it's no here page

- src/pages/settings/Security/TwoFactorAuth/Steps/SuccessStep.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> fix 2fa navi bug

- src/libs/Navigation/types.ts
- src/pages/workspace/expensifyCard/WorkspaceEditCardLimitPage.tsx
- src/pages/workspace/expensifyCard/WorkspaceEditCardLimitTypePage.tsx
- src/pages/workspace/expensifyCard/WorkspaceEditCardNamePage.tsx
- src/pages/workspace/expensifyCard/WorkspaceExpensifyCardDetailsPage.tsx
… type/Card name in card details page
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix issue: Expensify Card - App crashes when clicking Card limit/Limit type/Card name in card details page

- src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix issue: Workflows - RHP opens not here page when returning from Approver page

- src/ROUTES.ts
- src/libs/Navigation/types.ts
- src/pages/settings/Wallet/Card/BaseGetPhysicalCard.tsx
- src/pages/settings/Wallet/Card/GetPhysicalCardAddress.tsx
- src/pages/settings/Wallet/Card/GetPhysicalCardConfirm.tsx
- src/pages/settings/Wallet/Card/GetPhysicalCardName.tsx
- src/pages/settings/Wallet/Card/GetPhysicalCardPhone.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix get physical card navigation flow.

- src/components/PromotedActionsBar.tsx
During our navigation migration, we inversed one condition. It caused bugs with the display of the hold educational modal from the search.
$ https://github.com/Expensify/App/pull/49539#issuecomment-2603034456
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix issue: Hold modal

- src/libs/Navigation/AppNavigator/Navigators/ReportsSplitNavigator.tsx
- src/libs/ReportActionComposeFocusManager.ts
- src/libs/actions/Report.ts
- src/pages/home/report/PureReportActionItem.tsx
- src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx
- src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx
- src/pages/home/report/ReportActionItemMessageEdit.tsx
This PR fixes:
- Composer - Composer is not focused when starting a new chat: https://github.com/Expensify/App/pull/49539#issuecomment-2603059023
- Web / Desktop - Chat - Composer focus is lost after editing a message: https://github.com/Expensify/App/pull/49539#issuecomment-2603530641
Also while debugging logic around focusing Composer I found a bunch of places that could be simplified, so I did that. Some of the code was old, some parts were unnecessary.
https://github.com/user-attachments/assets/869b9904-b9bf-42af-850d-4f0f5e05f069
$ 
PROPOSAL:
> Fix composer focusing issues

- src/libs/CardUtils.ts
- src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix card not immediately appearing after assigning

- src/components/MoneyRequestConfirmationList.tsx
- src/components/MoneyRequestConfirmationListFooter.tsx
For some reason there were `getActiveRouteWithoutParams` used instead of `getActiveRoute`. 
This was creating the wrong `backTo` param that doesn't reflect the real params of the screen one route below. 
It lacked a param with a `?xz=true` notation. The `goBack` function behavior was broken because of that. Params comparison of the route from `backTo` and one route below was always falsy.
$ https://github.com/Expensify/App/pull/49539#issuecomment-2604645110
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Fix issue: Wrong return path after returning from receipt on confirm page when sharing with accountant

- src/pages/iou/request/step/IOURequestStepTime.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix per diem nav bug

- src/components/ScreenWrapper.tsx
- src/styles/index.ts
There was some timing issue with hiding the keyboard and displaying the bottom tab bar in the keyboard avoiding view. Now it's outside the avoiding view in the ScreenWrapper
$ https://github.com/Expensify/App/issues/55511#issuecomment-2629033744
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix issue: Android - Workspace - There are two bottom bars after creating a workspace

- src/libs/SearchUIUtils.ts
- src/pages/PrivateNotes/PrivateNotesEditPage.tsx
- src/pages/Search/AdvancedSearchFilters.tsx
…g filter and click View results
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix split navs issues

- src/ROUTES.ts
- src/pages/workspace/WorkspaceInviteMessagePage.tsx
- src/pages/workspace/tags/WorkspaceEditTagsPage.tsx
- src/pages/workspace/tags/WorkspaceViewTagsPage.tsx
The tags flow is weird. We may need to redo navigation for this part. The `backTo` parameter seems to be misused.
$ https://github.com/Expensify/App/issues/55511#issuecomment-2629091666
$ https://github.com/Expensify/App/issues/55511#issuecomment-2629091666
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix go backs for tags and workspace members

- src/components/ActiveWorkspaceProvider/index.tsx
- src/components/BlockingViews/ForceFullScreenView/index.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Review fixes

- src/components/ScreenWrapper.tsx
- src/styles/index.ts
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix showing bottom side of pages displayed in ScreenWrapper

- src/components/Navigation/TopLevelBottomTabBar/index.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Improve useEffect in TopLevelBottomTabBar

- src/components/Navigation/TopLevelBottomTabBar/getIsScreenWithBottomTabFocused.ts
- src/libs/Navigation/AppNavigator/FreezeWrapper/index.native.tsx
- src/libs/Navigation/AppNavigator/FreezeWrapper/index.tsx
- src/libs/Navigation/AppNavigator/createRootStackNavigator/types.ts
- src/libs/Navigation/AppNavigator/createSplitNavigator/SplitRouter.ts
- src/libs/actions/Report.ts
- src/pages/Search/SearchPage.tsx
- src/pages/settings/Profile/PersonalDetails/CountrySelectionPage.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Poc/fixes after review 

- src/pages/iou/request/step/IOURequestStepDestination.tsx
- src/pages/iou/request/step/IOURequestStepTime.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Add backTo when navigating to IOURequestStepTime

- src/libs/actions/App.ts
- src/pages/workspace/WorkspaceConfirmationPage.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix navigating from WorkspaceConfirmationPage on a wide layout

- src/components/MoneyReportHeader.tsx
- src/libs/ReportSecondaryActionUtils.ts
$ https://github.com/Expensify/App/issues/59877
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Delete option is present for approved expense which causes error when deleting itjnowakow/simplified-actions-on-header-v2

- src/components/EReceipt.tsx
- src/components/EReceiptWithSizeCalculation.tsx
- src/components/ReceiptEmptyState.tsx
- src/components/ReceiptImage.tsx
- src/components/ReportActionItem/ReportActionItemImage.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Add onLoad prop to EReceipt

- src/libs/Navigation/NavigationRoot.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Fix navigation theme on narrow layout

- src/components/Image/index.tsx
- src/components/Image/types.ts
- src/components/ReceiptImage.tsx
- src/components/ReportActionItem/ReportActionItemImage.tsx
$
PROPOSAL:
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Add shouldCalculateAspectRatioForWideImage prop to Image component
